### ISSUE TITLE
Retire this library?

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/Esplora#3]
The [Arduino Esplora](https://store.arduino.cc/arduino-esplora) has been retired, shall we archive this library @alranel ?

**Comment by RufusVS** [comment]
Just because the product has been retired, doesn't mean there aren't people using it that need this support.  What is the replacement alternative?

**Comment by aentinger** [comment]
As you can see @RufusVS , there's hardly a large number of outstanding issues. In any case my internal suggestion has always been - archive a repository and reopen, if there's someone interested in maintaining it. But alas, we didn't it archive yet, and I don't think it will happen anytime soon.

**Comment by alranel** [comment]
Yes, I'd say let's archive this repository. The library will still be available in the Library Manager for anyone. Archiving the repo is just a way to signal that we're not maintaining the code actively. As @aentinger was saying, if anyone from the community wants to volunteer, we'll happily un-archive it :)
